spring:
   jmx:
      default-domain: mephskeleton_restapi
   application:
      name: mephskeleton_restapi
logging:
  config: classpath:logback-spring.xml
info:
  app:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
endpoints:
  enabled: false
  health.enabled: true
  info.enabled: true
  metrics.enabled: true
management:
  endpoints:
    web:
      base-path: /