jasypt:
  encryptor:
    password: ${APP_ENC_CLASS:}
spring:
   datasource:
      url: ${MODEL_DATASOURCE_URL}
      username: ${MODEL_DATASOURCE_USER}
      password: ${MODEL_DATASOURCE_PASSWORD}
      driver-class-name: oracle.jdbc.driver.OracleDriver
      driver-name: oracle.jdbc.OracleDriver
      tomcat:
        initialSize: 10
        maxActive: 10
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 360000
        validationQuery: SELECT 'mephskeleton' FROM DUAL
   jpa:
      databasePlatform: org.hibernate.dialect.Oracle10gDialect
      show-sql: false
      hibernate:
         ddl-auto:
   jmx:
      default-domain: mephskeleton_restapi
   application:
      name: mephskeleton_restapi
flyway:
  enabled: false
hibernate:
  jdbc:
    batch_size: 1000
logging:
  config: classpath:logback-spring.xml
info:
  app:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
endpoints:
  enabled: false
  health.enabled: true
  info.enabled: true
  metrics.enabled: true
management:
  endpoints:
    web:
      base-path: /