apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: mephskeleton-restapi-pdb
  namespace: meph-integration 
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      k8s-app: mephskeleton-restapi
