spring:
   jmx:
      default-domain: mephmicroapi_restapi
   application:
      name: mephmicroapi_restapi
info:
  app:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
endpoints:
  enabled: false
  health.enabled: true
  info.enabled: true
  metrics.enabled: true
management:
  endpoints:
    web:
      base-path: /
