apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: mephmicroapi-restapi-pdb
  namespace: <k8s_namespace> 
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      k8s-app: mephmicroapi-restapi
