version: '3.4'
networks:
  test_integ_network:
    driver: bridge
  test_bakcend:
services:
  mephmicro_bbddtest:
    image: mephmicro_bbddtest
    labels:
      - "BBDDTEST"
    networks:
      test_bakcend:
        aliases:
          - mephmicro_bbddtest

  mephmicro_mockserver:
    image: mockhttp
    labels:
      - "MOCKSERVER"

    networks:
      test_bakcend:
        aliases:
          - mephmicro_mockserver
secrets:                        # top level secrets block
  mephmicro_bbdd_PASSWORD_SECRET:
    file: mockserver_password.txt
