FROM mhart/alpine-node:latest
#FROM library/alpine
#postman/newman_ubuntu1404

RUN npm install newman --global;
#
RUN mkdir /scripts
#
COPY test_integracion_scripts/* /scripts/
#
#CMD "read -n 1 espera"
