version: '3.4'
services:
  dummy_service_singleapp:
    depends_on:
      - dummy_service_bbddtest
      - dummy_service_mockserver
    networks:
      test_integ_network:
        aliases:
          - dummy_service_singleapp_external
      test_bakcend:
        aliases:
          - ${DOCKER_SINGLEAPP_IMAGE_NAME}
    secrets:                    # secrets block only for 'web' service
      - dummy_service_bbdd_PASSWORD_SECRET
