networks:
  test_bakcend: {}
  test_integ_network:
    driver: bridge
secrets:
  mephskeleton_bbdd_PASSWORD_SECRET:
    file: /c/eb2/git/mephskeleton/build_pipeline/stack_definitions/mockserver_password.txt
services:
  mephskeleton_bbddtest:
    image: mephskeleton_bbddtest
    labels:
      BBDDTEST: ''
    networks:
      test_bakcend:
        aliases:
        - mephskeleton_bbddtest
  mephskeleton_restapi:
    depends_on:
    - mephskeleton_bbddtest
    environment:
      ACTIVE_PROFILES: mock
      ENV_JAVA_OPTS: -XX:MaxRAM=384m -Xmx256m -Xms256m -agentlib:jdwp=transport=dt_socket,address=8091,server=y,suspend=n
      MODEL_DATASOURCE_URL: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=mephskeleton_bbddtest)(PORT=1521))(CONNECT_DATA=(service_name=xe)))
      MODEL_DATASOURCE_USER: DB_INTEG_USER
    healthcheck:
      test:
      - CMD
      - wget
      - --tries=1
      - --spider
      - http://localhost:8080/health
    image: mephskeleton-restapi:DEVELOP-SNAPSHOT.1558451460
    networks:
      test_bakcend:
        aliases:
        - mephskeleton-restapi
      test_integ_network:
        aliases:
        - mephskeleton_restapi_external
    ports:
    - published: 8888
      target: 8080
    secrets:
    - source: mephskeleton_bbdd_PASSWORD_SECRET
version: '3.4'

