FROM openjdk:13-alpine
MAINTAINER mephistos
ARG ORIGIN_JAR
ARG DESTINATION_JAR

VOLUME /var/log /var/log
COPY $ORIGIN_JAR /data/$DESTINATION_JAR
ADD ./image_scripts/*.sh /data/
RUN chmod 777 /data/*.sh;apk add zip; apk add unzip
CMD . /data/start_app.sh