apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: mephmicro-restapi-hpa
  namespace: <k8s_namespace>
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mephmicro-restapi-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
