apiVersion: apps/v1
kind: Deployment
metadata:
  name: <name>-deployment
  namespace: <namespace>
spec:
  selector:
    matchLabels:
      k8s-app: <name>
  template:
    metadata:
      labels:
        k8s-app: <name>
      annotations:
    spec:
      containers:
        - name: app
          envFrom:
            - configMapRef:
                name: configmap-<name>
          image: <docker-registry-domain-name>/<aplication-repo-name>:<version>
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            limits:
              cpu: <limit_cpu_value>
              memory: <limit_memory_value>
            requests:
              cpu: <request_cpu_value>
              memory: <request_memory_value>