pipeline {
    agent any

    environment {
        mvnhome= tool 'M3'
        PATH = "${mvnhome}/bin:$PATH"
        ENVIRONMENT= "${env.ENVIRONMENT}"
        BRANCH="${env.BRANCH_NAME}"
    }

    stages
    {
        stage('Pipeline initialization') {
           steps
           {
                dir('./build_pipeline') {
                    sh 'chmod 770 *.sh'
                }
           }
        }

        stage('Build software') {
           steps
           {
                dir('./build_pipeline') {
                    sh 'export PATH="${mvnhome}:$PATH" && ./01_01_build_software.sh -f jenkins'
                }
           }
        }

        stage('Unit Test') {
           steps
           {
                dir('./build_pipeline') {
                    sh 'export PATH="${mvnhome}:$PATH" && ./01_02_build_unit_tests.sh -f jenkins'
                }
           }
        }

        stage('Build Images') {
           steps
           {
                dir('./build_pipeline') {
                    sh './02_docker_build_images.sh'
                }
           }
        }
    }
}